import { GoogleGenAI, Type } from "@google/genai";
import { RewriteOptions, HumanizationResult, Voice } from '../types';

// As per instructions, I must use process.env.API_KEY
// and assume it's configured.
const apiKey = process.env.API_KEY;
if (!apiKey) {
    // This provides a clear error for developers if the key is missing.
    // In a production environment, this variable is expected to be set.
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey });

const responseSchema = {
    type: Type.OBJECT,
    properties: {
        rewrittenText: {
            type: Type.STRING,
            description: "The full, rewritten text."
        },
        statistics: {
            type: Type.OBJECT,
            properties: {
                totalChanges: { type: Type.INTEGER, description: "Total number of significant edits made."},
                phrasesReplaced: { type: Type.INTEGER, description: "Number of common 'AI-sounding' or robotic phrases replaced."},
                contractionsAdded: { type: Type.INTEGER, description: "Number of contractions (e.g., 'do not' to 'don't') added to make the text more casual."}
            },
            required: ["totalChanges", "phrasesReplaced", "contractionsAdded"]
        },
        changes: {
            type: Type.ARRAY,
            description: "An array of objects detailing significant changes made.",
            items: {
                type: Type.OBJECT,
                properties: {
                    type: {
                        type: Type.STRING,
                        description: "The category of change. Examples: 'REPHRASE', 'ADD_CONTRACTION', 'REMOVE_PHRASE', 'IMPROVE_FLOW', 'EXPAND'."
                    },
                    originalText: {
                        type: Type.STRING,
                        description: "The original phrase or sentence fragment that was changed. Should be an exact match from the source text."
                    },
                    humanizedText: {
                        type: Type.STRING,
                        description: "The new, rewritten phrase or sentence fragment. This text appears in the final `rewrittenText`."
                    },
                    explanation: {
                        type: Type.STRING,
                        description: "A brief explanation of why the change was made."
                    }
                },
                required: ['type', 'originalText', 'humanizedText', 'explanation']
            }
        }
    },
    required: ['rewrittenText', 'statistics', 'changes']
};

const getToneAndVoiceInstruction = (options: RewriteOptions): string => {
    // Handle the specialized "Researcher Mode"
    if (options.tone === 'researcher' && options.voice === 'objective') {
        return `You are now writing in "Researcher Mode". Adopt the voice of an experienced academic researcher: analytical, precise, and objective — but written in a natural, human rhythm. Your sentences must feel authored by a thoughtful human, not generated by a pattern-based model.

**Core Writing Behaviors:**
1. Write with *measured variation*: alternate sentence length, structure, and tone to avoid uniformity.
2. Use formal academic diction but remain readable and fluent.
3. Integrate cautious qualifiers typical of research writing (e.g., “may suggest,” “is likely,” “could imply”).
4. Maintain logical transitions (e.g., “however,” “in contrast,” “furthermore,” “notably”).
5. Show reasoning, not templates — paraphrase concepts instead of repeating identical structures.
6. Avoid repetitive connectors, redundant adverbs, and symmetrical phrasing that signal AI patterns.
7. Use domain-accurate terminology and concise factual statements.
8. Employ active or passive voice strategically (alternate between them to keep flow natural).
9. Avoid filler, clichés, and “In conclusion”-type phrases unless contextually necessary.
10. Ensure clarity, coherence, and natural pacing while preserving original meaning.

**Stylistic Identity:**
- Tone: formal, confident, evidence-based
- Register: academic but human
- Sentence rhythm: diverse (e.g., alternating between long analytical sentences and shorter, direct statements).`;
    }

    // Fallback logic for other combinations
    let voiceInstruction: string;
    switch (options.voice) {
        case 'first-person':
            voiceInstruction = "write from a first-person perspective (e.g., using 'I', 'we').";
            break;
        case 'third-person':
            voiceInstruction = "write from a third-person perspective (e.g., using 'he', 'she', 'they', 'the author').";
            break;
        case 'objective':
             voiceInstruction = "write from an objective and impersonal perspective. Avoid personal pronouns like 'I' or 'we', and use passive voice where stylistically appropriate for formal, academic, or scientific writing.";
             break;
        default:
            voiceInstruction = `write from a ${options.voice} perspective.`;
            break;
    }

    if (options.tone === 'researcher') {
        return `Adopt a formal, objective, and precise researcher writing style. The tone should be scholarly and suitable for academic papers, research reports, or scientific journals. Focus on clarity, accuracy, and evidence-based language. Avoid colloquialisms and overly casual phrasing. Regarding the voice, ${voiceInstruction}`;
    }
    
    return `Use a ${options.tone} tone. Regarding the voice, ${voiceInstruction}`;
};


export const humanizeText = async (
    originalText: string,
    options: RewriteOptions
): Promise<HumanizationResult> => {
    
    const toneAndVoiceInstruction = getToneAndVoiceInstruction(options);
    const expansionInstruction = options.expand
        ? "Additionally, expand upon the original text. Add relevant details, provide illustrative examples, or elaborate on key points to make the content more comprehensive and insightful. The goal is to enrich the text while maintaining the specified tone and voice, ensuring the expansion is natural and coherent."
        : "Focus solely on rewriting the existing text for clarity, flow, and tone. Do not add new information or significantly expand the content.";

    const prompt = `
        You are an expert writer tasked with rewriting text to make it sound more natural and human-like, while adhering to specific stylistic constraints.
        Your goal is to eliminate any awkward phrasing, unnatural sentence structures, or robotic tone.
        
        Please rewrite the following text.
        
        **Instructions:**
        1.  **Core Task:** ${expansionInstruction}
        2.  **Preserve Core Meaning:** The original message must remain the foundation of the rewritten text.
        3.  **Improve Flow:** Make the text smoother and easier to read.
        4.  **Tone and Voice:** ${toneAndVoiceInstruction}
        5.  **Analyze Changes:** Identify every significant change you make. For each change, detail the original text fragment, the new humanized fragment, the type of change, and a brief explanation. If you are expanding the text, categorize additions as 'EXPAND' type changes.
        6.  **Calculate Statistics:** Provide a count of total changes, robotic phrases replaced, and contractions added. If the tone is 'researcher' or 'academic', or if the voice is 'objective', the number of contractions added should typically be zero.
        7.  **JSON Output:** You MUST respond with a single JSON object. Do not add any text before or after the JSON.
        8.  The JSON object must have three top-level keys: "rewrittenText", "statistics", and "changes".
        
        **Original Text:**
        ---
        ${originalText}
        ---
    `;

    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: responseSchema,
            },
        });

        const jsonText = response.text;

        if (!jsonText) {
            throw new Error('No content was generated.');
        }
        
        const apiResult = JSON.parse(jsonText);
        
        if (!apiResult.rewrittenText || !apiResult.statistics || !Array.isArray(apiResult.changes)) {
             throw new Error("Invalid JSON structure received from API.");
        }

        // Map the API response to the app's internal type `HumanizationResult`
        return {
            text: apiResult.rewrittenText,
            changes: apiResult.changes,
            stats: apiResult.statistics,
        };

    } catch (error: any) {
        console.error("Error calling Gemini API:", error);
        if (error.message.includes("JSON")) {
            throw new Error("Failed to get a valid analysis from the AI. The response was not in the expected format.");
        }
        throw new Error("Failed to humanize text due to an API error. Please try again later.");
    }
};
